rust-bitcoin/corepc

types/src/v17/mod.rs
Make the docs easier to read in HTML by using drop down menus and tabulating the method name and status. If docs were able to be sexy then these ones right here.
=> types: Tabulate the v17 docs

integration_test/Cargo.toml, node/Cargo.toml, node/src/client_versions.rs, node/src/versions.rs
Add support for minor release of v27. Nothing much to do except update all the manifest infrastructure and add the version-specific re-exports from `client`.
Close: #3
=> Add support for Bitcoin Core v27.2

types/src/v17/wallet/into.rs
We provide `From` impls for all errors that include a `NumericError` - use it.
=> Do not manually map numeric error

client/src/client_sync/v28/mod.rs, client/src/client_sync/v28/raw_transactions.rs, integration_test/src/lib.rs, integration_test/tests/raw_transactions.rs, types/src/model/mod.rs, types/src/model/raw_transactions.rs, types/src/v28/mod.rs, types/src/v28/raw_transactions/error.rs, types/src/v28/raw_transactions/into.rs, types/src/v28/raw_transactions/mod.rs
Bitcoin Core introduced a new RPC method `submitpackage`. Add support for it including integration testing.
This work was originally done by tnull a while ago over on the old `rust-bitcoind-json-rpc` repository (PR: https://github.com/rust-bitcoin/rust-bitcoind-json-rpc/pull/23).
I took his changes and updated the code with the ideas I've learned recently fleshing out v17.
Patch includes `<Co-developed-by>` tag.
Close: #7
=> v28: Add support for `submitpackage`

types/src/v17/blockchain/into.rs
=> Use `parse::<Txid>()` in place of `encode::deserialize_hex()`

node/src/lib.rs
Closes #19 
Users may construct `serde_json::Value` to use with `Client::call`.
=> Public export of `serde_json`

contrib/run-bitcoind.sh
Currently we have one script that uses dashes and one using underscores. Dashes or underscores it doesn't matter, just use one.
Use dashes because it makes me feel like a lisp hacker.
=> Rename script to use dash

client/src/client_sync/v17/wallet.rs, integration_test/tests/raw_transactions.rs, integration_test/tests/wallet.rs, types/src/v17/mod.rs, types/src/v18/mod.rs
There are a couple of problems highlighted when one runs `verify v17` - fix them. Includes fix the client and integration test around the `getreceivedbyaddresses` method.
=> Fix up `verify v17`

node/Cargo.toml
I don't think this actually makes any difference but it saves me doing it again later.
=> node: Use latest version in docs build

.github/workflows/README.md, .github/workflows/rust.yaml, Cargo-minimal.lock, Cargo-recent.lock, Cargo.toml, verify/Cargo.toml, verify/src/main.rs
The `verify` crate is a dev tool and should not have been included in the workspace because it has no lock file requirements.
Exclude `verify` from the workspace and update the lock files and add a job that runs it from CI.
=> Run `verify` in CI

Cargo-minimal.lock, Cargo-recent.lock, client/CHANGELOG.md, client/Cargo.toml, integration_test/Cargo.toml, node/CHANGELOG.md, node/Cargo.toml, types/CHANGELOG.md, types/Cargo.toml
In preparation for releasing all three crates bump the version, add a changlog entry, and update the lock files.
For the record this release of `types` will include fleshed out support in `types` for v17 and v18.
=> Release tracking PR: Bump versions to 0.5.0

types/src/v17/mod.rs, types/src/v18/mod.rs, verify/src/main.rs
Currently the verify integration test code is broken because it greps for test names not bothering that some may be feature gated.
Instead of grepping for integration tests by name instead accept an option that includes a file that is the output from running the integration tests and then grep that file.
=> Verify integration tests using output of test file

Cargo-minimal.lock, Cargo-recent.lock, types/Cargo.toml, types/src/error.rs, types/src/lib.rs, types/src/model/blockchain.rs, types/src/model/raw_transactions.rs, types/src/model/wallet.rs, types/src/v17/blockchain/error.rs, types/src/v17/blockchain/mod.rs, types/src/v17/control.rs, types/src/v17/network/error.rs, types/src/v17/network/mod.rs, types/src/v17/wallet/error.rs, types/src/v17/wallet/mod.rs, types/src/v19/blockchain.rs, types/src/v28/blockchain.rs, types/src/v28/raw_transactions/error.rs, types/src/v28/raw_transactions/mod.rs
`master` is currently broken because the linter is warning because of a `std` feature (which is coming from our usage of `internals::write_err`).
We can fix this breakage after observing that calling macros from other crates is error prone. Lets copy the macro. On the way add a `std` feature and stop using `HashMap`.
This also allows the removal of the `internals` dependency. Sexy PR right here.
Close: #12
=> Add `std` feature

node/src/lib.rs
This test works for `28_0`. It does not need feature gating out.
The reason this was done is because it cannot be run in parallel with `test_multi_p2p`. We can leave that one feature guarded out in v28 builds.
The underlying issue is a problem with how Bitcoin Core binds to ports and is tracked in #41
=> Remove feature gating from `test_p2p` unit test

README.md
This PR addresses a typo in the crate name `rust-bitcoincore-rpc` in the `README.md` file.
=> Fix typo in crate name in `README.md`

node/src/lib.rs
Currently the `node` crate cannot run multiple instances of Bitcoin Core v28 because of changes to bind logic in that release.
The solution is to use `-bind` instead of `-port`.
For more information on the relevant changes in Core v28 see:
https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-28.0.md#p2p-and-network-changes
This patch was created with help of MaxFangX - mad props.
Fix: #41
=> Enable running multiple Core v28 nodes

README.md, client/README.md, node/README.md, types/README.md
Improve docs:
- repo docs
- MSRV docs
- `types` docs
=> Improve the docs

integration_test/Cargo.toml, node/Cargo.toml, node/src/client_versions.rs, node/src/versions.rs
The default feature in node overides an explicit version feature. This is a footgun. Currently the logic around using `bitcoind` from the environment is borked.
Also, features in the `node` crate are unusual in that at least one version feature is expected. Lets make this a build requirement.
Maintain the current behaviour in relation to `--all-features` i.e., all features implies latest version 28.0
- Remove `default` feature
- Remove `download` from version number features
- Use `compile_error` to catch missing version feature
Fix: #40
=> node: Remove `default` feature

node/Cargo.toml
Quick cleanup to the `node` manifest. Done while working on #53
=> Clean up the `node` manifest

integration_test/tests/wallet.rs
Do some trivial integration test clean ups.
=> Clean up tests

client/src/client_sync/v17/generating.rs, client/src/client_sync/v17/mod.rs, client/src/client_sync/v18.rs, client/src/client_sync/v19/mod.rs, client/src/client_sync/v20.rs, client/src/client_sync/v21.rs, client/src/client_sync/v22/mod.rs, client/src/client_sync/v23.rs, client/src/client_sync/v24.rs, client/src/client_sync/v25.rs, client/src/client_sync/v26.rs, client/src/client_sync/v27.rs, client/src/client_sync/v28/mod.rs, integration_test/tests/generating.rs
Fixes #67.
While this is RPC call is not listed as part of the official RPC API, we add support here as it can be crucial for regtest testing (e.g. writing reorg tests).
=> Add support for `invalidateblock`

.github/workflows/rust.yaml, Cargo-minimal.lock, Cargo-recent.lock, Cargo.toml, integration_test/Cargo.toml, justfile, node/Cargo.toml, node/README.md, node/build.rs, node/contrib/extra_tests.sh, node/contrib/test_vars.sh, node/src/client_versions.rs, node/src/lib.rs, node/src/versions.rs
Currently we do not include the `node` crate in the workspace because `run_task` did not support testing it.
However `run_task` has been patched. Additionally we discovered that we were not _testing_ the docs with `--all-features` (or any code for that matter other than linting). Fixed in:
https://github.com/rust-bitcoin/rust-bitcoin-maintainer-tools/pull/20
Which this patch uses.
Include `node` in the workspace. Configure it to work with the newly patched `run_task`. Add a `extra_tests.sh` script that runs the `node` tests.
In order to get MSRV building we make all deps use `default-features = false` then explicitly enable just what we need.
Also change the feature guarding in the build script so that `--all-features` works. This is already supported in the main crate code since the …
=> Include `node` in workspace

Cargo-minimal.lock, Cargo-recent.lock, jsonrpc/Cargo.toml, jsonrpc/src/http/minreq_http.rs, jsonrpc/src/http/simple_http.rs
This is just simple dependency update to avoid people having duplicate (old) versions of base64 in their dependency tree if they use this crate.
=> Update to base64 0.22.1

Cargo-minimal.lock, Cargo-recent.lock, client/CHANGELOG.md, client/Cargo.toml, integration_test/Cargo.toml, node/CHANGELOG.md, node/Cargo.toml, types/CHANGELOG.md, types/Cargo.toml, verify/README.md
In preparation for release of all three crates add changelog entries, bump the version number, and update the lock files.
Patch 2 closes #69
=> Release tracking PR: `v0.6.0`

integration_test/src/lib.rs, integration_test/tests/blockchain.rs, types/src/v18/mod.rs
The `getblockstats` method works for some versions of Core and not others.
- Refactor the tests to try and make it more clear exactly when the method is tested.
- Enable testing for `v18` with and without `-txindex` for versions that support it.
- Enable testing of `v18` with `-txindex`
- Update the rustdocs in `types` to show that its tested for `v18`.
- Mine a block before getting the stats, no real reason but just because the comments mention the genesis block.
FTR I'm not totally across exactly why this works for v17 and v18 and then not until v25 again.
=> Refactor `getblockstats` tests and enable for v18

verify/src/lib.rs
We have a bunch of false positives when verifying types in the version they are defined because the re-export is of form:
```rust
pub use self::control::Logging;
```
Add a semicolon to the regex.
=> verify: Include trailing semicolon

node/build.rs
Previously, using the (node) crate with the `from_downloaded()` trait would fail on apple silicon with `bad CPU type in executable`
Part of the update includes some code-signing, this is necessary for unsigned binaries (like bitcoind) to run on Arm Macs:
https://github.com/bitcoin/bitcoin/pull/26694#issuecomment-1348887186
=> Fix to download the correct binary for Apple silicon Macs

node/Cargo.toml, node/README.md, node/build.rs
Currently the docs.rs build is not working. From the log it can be seen that the build is trying to download a bitcoind binary. I cannot see why this is happening, it does not happen locally. Anyway we can just change the docs build to use `28_0` instead of all features and this bypasses the problem.
While we are at it, change the feature gating in `build.rs` on the `download` module because it still seems wrong. Phew logically combining negative truth values is hard to reason about.
=> node: Fix the rustdocs build

types/src/model/wallet.rs, types/src/v17/wallet/into.rs, types/src/v17/wallet/mod.rs
This is a backport of the single patch in #89.
Contrary to Bitcoin Core's v17 docs, there are *5* transaction categories that might be returned as part of a response to `listtransactions`, `listsinceblock`, or `gettransaction`. While Core fixed this omission in the docs in https://github.com/bitcoin/bitcoin/pull/14653, we didn't account for them in the respective model's `enum`, leading to calls to `get_transaction` randomly failing with the rather obscure error message:
```
Err(JsonRpc(Json(Error("unknown variant `generate`, expected `send` or `receive`", line: 1, column: 682))))
```
Here, we fix this omission and add the missing categories.
=> backport: Add missing transaction categories

node/Cargo.toml, node/README.md, node/build.rs
This is a backport of the single patch in #90
Currently the docs.rs build is not working. From the log it can be seen that the build is trying to download a bitcoind binary. I cannot see why this is happening, it does not happen locally. Anyway we can just change the docs build to use `28_0` instead of all features and this bypasses the problem.
While we are at it, change the feature gating in `build.rs` on the `download` module because it still seems wrong. Phew logically combining negative truth values is hard to reason about.
=> backport: node: Fix the rustdocs build

types/src/model/wallet.rs, types/src/v17/wallet/into.rs, types/src/v17/wallet/mod.rs
Fix a code comment mistake then change the `model` for `GetTransaction` to use a signed amount.
This is a bug fix.
Close: #80
=> Use `SignedAmount` when converting `gettransaction` amount to model 

Cargo-minimal.lock, Cargo-recent.lock, integration_test/Cargo.toml, node/CHANGELOG.md, node/Cargo.toml, types/CHANGELOG.md
We would like to do a point release of `node` and `type`s.
- `node`: to fix the docs.rs build
- `types`: to get the bug fix to transaction categories
To each crate add a changelog entry, bump the version, and update the  lock files.
=> Release tracking PR: `node` and `types` both to `v0.6.1`

Cargo-minimal.lock, Cargo-recent.lock, client/Cargo.toml, types/Cargo.toml
I just did a patch to bump the version of `node` and `types` but only added the changelog for `types` and forgot to actually bump the version - face palm.
Bump the version to 0.6.1 ready for release. Explicitly depend on the new version. Update the lock files.
=> types: Really bump version

client/Cargo.toml
The `client` is std only but we don't enable the `std` feature in `types` - this is a bug.
Fix: #97
=> client: Enable `std` feature in `types` crate

client/Cargo.toml
Backport single patch from #98 - I couldn't get `git cherry-pick` to work for some reason so I did this manually.
The `client` is std only but we don't enable the `std` feature in `types` - this is a bug.
Fix: #97
=> backport: client: Enable std feature in types crate

Cargo-minimal.lock, Cargo-recent.lock, client/CHANGELOG.md, client/Cargo.toml, integration_test/Cargo.toml, node/Cargo.toml
In preparation for release bump the version, add a changelog entry, and update the lock files.
=> client: Bump version to 0.6.1

Cargo-minimal.lock, Cargo-recent.lock, client/CHANGELOG.md, client/Cargo.toml, integration_test/Cargo.toml, node/CHANGELOG.md, node/Cargo.toml, types/CHANGELOG.md, types/Cargo.toml
Bring the changelog entries from all the 0.6.1 releases over to master. While we are at it update versions and explicitly depend on the latest version for all three released crates.
=> Update changelogs for 0.6.1 changes

integration_test/src/lib.rs, integration_test/tests/blockchain.rs, types/src/v19/mod.rs, types/src/v20/mod.rs, types/src/v21/mod.rs, types/src/v22/mod.rs, types/src/v23/mod.rs, types/src/v24/mod.rs, types/src/v25/mod.rs, types/src/v26/mod.rs, types/src/v27/mod.rs, types/src/v28/mod.rs
I was confused by `getblockstats` not working and thought it did not work for version 19-24 however there was a bug in a helper function that meant we always tried to get block stats for the genesis block and this does not work for these versions. That bug is fixed in patch 2 then in patch 3 we test and set the status of `getblockstats` for all versions.
Patch 1 is a trivial cleanup to the `NodeExt` constructors. Unrelated but done while debugging this.
=> Test `getblockstats` for all versions

integration_test/tests/wallet.rs, types/src/v26/mod.rs, types/src/v26/wallet.rs, types/src/v27/mod.rs, types/src/v28/mod.rs
With `v25` the `warning` field was deprecated for `warnings`. While it should only be available when the `-deprecatedrpc=walletwarningfield` is passed, I was hitting parse errors even though I did not find where I
passed this argument. Here, we add the `warning` field to the `v25` types (although we ignore it as it's literally duplicative of what's in `warnings` already) to avoid the parse error.
=> Fix `{create,load}wallet` on `v25`

client/src/client_sync/v17/mod.rs, client/src/client_sync/v17/wallet.rs, client/src/client_sync/v18/mod.rs, client/src/client_sync/v19/mod.rs, client/src/client_sync/v20.rs, client/src/client_sync/v21/mod.rs, client/src/client_sync/v21/wallet.rs, client/src/client_sync/v22/mod.rs, client/src/client_sync/v23.rs, client/src/client_sync/v24.rs, client/src/client_sync/v25.rs, client/src/client_sync/v26/mod.rs, client/src/client_sync/v27.rs, client/src/client_sync/v28/mod.rs, integration_test/tests/wallet.rs, types/src/v17/mod.rs, types/src/v18/mod.rs, types/src/v19/mod.rs, types/src/v20/mod.rs, types/src/v22/mod.rs, types/src/v23/mod.rs, types/src/v24/mod.rs, types/src/v25/mod.rs, types/src/v25/wallet.rs, types/src/v26/mod.rs, types/src/v26/wallet.rs, types/src/v27/mod.rs, types/src/v28/mod.rs
Starting at Core version 21 the `unloadwallet` method starts returning a json object (with warnings in it). Prior to v21 it returned null.
There is a mistake in the client currently, the `unloadwallet` method is changed in v22 but should have been in v21.
Fix up the types, the client implementation, and the integration tests to fully test unload.
Add an integration test function that creates, loads, unloads a random wallet.
As a side note, keep the test names `load_wallet`, `unload_wallet` and call the other function - this is done so that the tests can be verified with the `verify` tool.
=> Fix `unloadwallet` method

node/src/lib.rs
I'm not sure what of the behavior really changed since the `bitcoind` days, but here's yet another thing I stumbled across while trying to making the switch to `corepc-node`:
Previously, `corerpc-node` would try to establish a connection via the given `Auth` cookie, and would panic if it couldn't setup a initial connection. Only the rest of the initial setup steps would be retried with time-delay.
This however was race-y, as the auth cookie might not already be synced to disk on first startup of a fresh `bitcoind` instance (with fresh data dir), when we try to connect for the first time. Here, we move the intial connection logic into the retry loop to simply also retry it instead of panicking.
@tcharding Seems this might be the last issue (fingers crossed) that keeps LDK and LDK Node from …
=> Retry initial client connections

Cargo-minimal.lock, Cargo-recent.lock, client/CHANGELOG.md, client/Cargo.toml, integration_test/Cargo.toml, node/CHANGELOG.md, node/Cargo.toml, types/CHANGELOG.md, types/Cargo.toml
In preparation for releasing all three crates; add changelog entries, bump the version number, and update the lock files.
=> Bump version number to 0.7.0 in all three crates

verify/src/main.rs
```shell
verify v1234
Unrecognised version: v1234 (supported versions: v17 - v28)
```
This removes the noise of listing all versions by displaying a concise version range.
Closes #65
=> simplify error message output for unsupported version output

contrib/run-bitcoind.sh
**Problem:**  
The script previously hardcoded version numbers and assumed specific directory structures in `/opt/`, making updates difficult and breaking user environments when new versions were introduced. Developers had to modify the script manually whenever a new version was released or when `bitcoind` was installed in a different location.  
**Solution:**  
This PR removes the hardcoded version numbers and introduces a configuration-based approach. The script now loads version numbers and `bitcoind` paths from either:  
1. A **custom environment variable** (`BITCOIND_VERSIONS_CONFIG`), allowing users to specify their own config file location.  
2. A **configuration file** (`bitcoind_versions.conf`), which developers can set up based on their local environment.  
If no custom …
=> Decouple version numbers for maintainability

Cargo-minimal.lock, Cargo-recent.lock, node/Cargo.toml
.. and in particular the ancient `time` dependency, which suffers from `RUSTSEC-2020-0071`.
(we recently started getting `cargo audit` reports related to this: https://github.com/lightningdevkit/ldk-node/issues/523)
=> Drop default features for `zip`

node/src/versions.rs
When running with the "27_2" feature flag enabled, the VERSION constant was incorrectly set to "27.1". This PR fixes the version string to properly reflect "27.2" when the corresponding feature flag is active.
=> Fix version for 27.2 feature flag

client/src/client_sync/error.rs
This commit removes the `Secp256k1` and `InvalidAmount` variants, their `From` impls, and updates the `Display` and `Error::source` methods accordingly.
Closes #119
=> Remove unnecessary error variants

types/src/model/mod.rs, verify/src/main.rs, verify/src/method/v19.rs, verify/src/model.rs
If a method does not require a model we currently do not check this. Add logic to do so.
Fix the warnings found:
- Re-export `ListUnspent`
- Use the correct `Method` constructor in v19
Fix: #70
=> verify: Check that no model type exists

integration_test/tests/wallet.rs, types/src/model/mod.rs, types/src/model/wallet.rs, types/src/v17/wallet/into.rs, verify/src/method/v17.rs, verify/src/method/v18.rs, verify/src/method/v19.rs, verify/src/method/v20.rs, verify/src/method/v21.rs, verify/src/method/v22.rs, verify/src/method/v23.rs, verify/src/method/v24.rs, verify/src/method/v25.rs, verify/src/method/v26.rs, verify/src/method/v27.rs, verify/src/method/v28.rs
The `dumpwallet` method returns a filename, this is not a `rust-bitcoin` type so there should not be a modelled version of the `DumpWallet` type.
=> Remove model for dumpwallet

verify/src/method/v19.rs, verify/src/method/v20.rs, verify/src/method/v21.rs, verify/src/method/v22.rs, verify/src/method/v23.rs, verify/src/method/v24.rs, verify/src/method/v25.rs, verify/src/method/v26.rs, verify/src/method/v27.rs, verify/src/method/v28.rs
Break the sections up by adding comments. This was done already for v17 and v18 but not the rest.
Includes reorder of incorrectly ordered `getrpcinfo` to maintain the same order as output by `bitcoin-cli help`.
=> verify: Comment sections

types/src/v17/mod.rs, types/src/v18/mod.rs, types/src/v19/mod.rs, types/src/v20/mod.rs, types/src/v21/mod.rs, types/src/v22/mod.rs, types/src/v23/mod.rs, types/src/v24/mod.rs, types/src/v25/mod.rs, types/src/v26/mod.rs, types/src/v27/mod.rs, types/src/v28/mod.rs, verify/src/versioned.rs
The module docs in each version specific module (e.g. `types::v17`) are supposed to be the single source of truth for devs trying to work out which methods are supported and how.
Make an effort to better present the information.
Note that a bunch docs for methods marked as TODO may be incorrect re version vs version + model. This doesn't matter right now since they will be checked when implemented and also TODO implies no guarantees (in my mind anyway).
Note also issue #144. `verify` does not check the Returns column against the `Method` constructor type.
Close: #109
=> types: Improve the version specific SSOT docs

Cargo-minimal.lock, Cargo-recent.lock, node/Cargo.toml
There's a RUSTSEC advisory on time that should be updated to >=0.2.23. It gets pulled down from corepc-node with download feature from the zip dependency, see the cargo tree below:
```
time 0.1.45
└── zip 0.5.13
└── corepc-node 0.7.0
```
Hence we need to update the zip dependency.
I don't know how to generate the `Cargo-*.lock` files.
Can you please advise?
Refs: https://rustsec.org/advisories/RUSTSEC-2020-0071
=> chore(deps): bump zip in light of RUSTSEC-2020-0071

Cargo-minimal.lock, Cargo-recent.lock, node/Cargo.toml
This is a backport of #143, done manually but originally authored by Jose.
--
There's a RUSTSEC advisory on time that should be updated to >=0.2.23. It gets pulled down from corepc-node with download feature from the zip dependency, see the cargo tree below:
```
time 0.1.45
└── zip 0.5.13
└── corepc-node 0.7.0
```
Hence we need to update the zip dependency.
=> backport: bump zip in light of RUSTSEC-2020-0071

Cargo-minimal.lock, Cargo-recent.lock, integration_test/Cargo.toml, node/CHANGELOG.md, node/Cargo.toml
In preparation for release bump the version, add a changelog entry, and update the lock files.
Release contains a single security patch.
=> node: Bump version to 0.7.1

node/CHANGELOG.md
We just did a point release. Copy the release notes to master (and pat myself on the back for remembering).
=> node: Copy point release notes

client/src/client_sync/mod.rs, client/src/client_sync/v17/mining.rs, client/src/client_sync/v17/mod.rs, client/src/client_sync/v18/mod.rs, client/src/client_sync/v19/mod.rs, client/src/client_sync/v20.rs, client/src/client_sync/v21/mod.rs, client/src/client_sync/v22/mod.rs, client/src/client_sync/v23/mod.rs, client/src/client_sync/v24.rs, client/src/client_sync/v25.rs, client/src/client_sync/v26/mod.rs, client/src/client_sync/v27.rs, client/src/client_sync/v28/mod.rs, integration_test/tests/mining.rs, node/src/client_versions.rs, node/src/lib.rs
This pull request moves the `TemplateRequest` struct and `TemplateRules` enum, into their appropriate module to improve code organization and maintainability.
=> Move TemplateRequest and TemplateRules into their proper module

types/src/v17/network/mod.rs
This comment is not true. `GetBlockcahinInfo` implements `into_model`. Furthermore the `///` after `//!` with no newline is weird.
Remove the comment all together.
=> Remove stale comment

integration_test/README.md
Our current setup supports running the integration tests using a local Core binary but the way to do so may not be obvious. So much so that I myself have been downloading in each worktree.
Add a README to document how to speed up local dev.
=> Document local integration test strategy

client/src/client_sync/mod.rs, client/src/client_sync/v17/mod.rs, client/src/client_sync/v17/raw_transactions.rs, client/src/client_sync/v17/wallet.rs, client/src/client_sync/v18/mod.rs, client/src/client_sync/v19/mod.rs, client/src/client_sync/v20.rs, client/src/client_sync/v21/mod.rs, client/src/client_sync/v22/mod.rs, client/src/client_sync/v23/mod.rs, client/src/client_sync/v24.rs, client/src/client_sync/v25.rs, client/src/client_sync/v26/mod.rs, client/src/client_sync/v27.rs, client/src/client_sync/v28/mod.rs, integration_test/tests/mining.rs, integration_test/tests/raw_transactions.rs, integration_test/tests/wallet.rs, node/src/client_versions.rs, node/src/lib.rs
Currently we have a bit of confusion around types that are defined and used by the various client version modules.
- Some currently don't change e.g., `Input`
- Some are due to change in v29 e.g., `TemplateRequest`
- Some change already e.g. `AddressVersion`
And to make matters worse, I did 'custom' re-exports in `node` which is very confusing when one is reading code in `client`.
Put all `client` defined types in the version module they first appear in and re-export them as we do for types from `types`. Then use the type naked (without qualifying the path).
=> client: Move types to version specific module

client/src/client_sync/v18/mod.rs, client/src/client_sync/v18/network.rs, client/src/client_sync/v19/mod.rs, client/src/client_sync/v20.rs, client/src/client_sync/v21/mod.rs, client/src/client_sync/v22/mod.rs, client/src/client_sync/v23/mod.rs, client/src/client_sync/v24.rs, client/src/client_sync/v25.rs, client/src/client_sync/v26/mod.rs, client/src/client_sync/v27.rs, client/src/client_sync/v28/mod.rs, integration_test/tests/network.rs, types/src/v18/mod.rs, types/src/v18/network/mod.rs, types/src/v19/mod.rs, types/src/v20/mod.rs, types/src/v21/mod.rs, types/src/v22/mod.rs, types/src/v23/mod.rs, types/src/v24/mod.rs, types/src/v25/mod.rs, types/src/v26/mod.rs, types/src/v27/mod.rs, types/src/v28/mod.rs
Implement the `getnodeaddresses` method added in V18, including integration test and reexports in newer versions.
=> Implement getnodeaddresses method and test

contrib/run-bitcoind.sh
This got deleted somehow and its still used. I was surprised that `shellcheck` does not find this, I would have thought a shell linter would have access to `$PATH` and be able to tell that the function does not exist. Anywho, add the function back in from a previous release.
Fix: #168
=> run-bitcoind: Add err function back in

contrib/run-bitcoind.sh, node/contrib/extra_tests.sh
Core v28 introduced changes making node startup fail if bind fails. We fixed this in `node` in #46 but in `run-bitcoind.sh` we still use `-port`. This didn't cause any problems because we only pass the arg to one of the two nodes so port 18445 was available. When we try to add support for v29 things break.
Jamil was experiencing this problem (I think) while running v28 nodes but I don't know why.
Use `-bind` instead of `-port`.
=> run-bitcoind: Fix startup of Core nodes

integration_test/tests/wallet.rs, types/Cargo.toml, types/src/model/wallet.rs, types/src/v17/mod.rs, types/src/v17/wallet/into.rs, types/src/v18/mod.rs, types/src/v19/mod.rs, types/src/v20/mod.rs, types/src/v21/mod.rs, types/src/v22/mod.rs, types/src/v23/mod.rs, types/src/v24/mod.rs, types/src/v25/mod.rs, types/src/v26/mod.rs, types/src/v27/mod.rs, types/src/v28/mod.rs
Change the strong type of the returned signature to `MessageSignature` to match `signmessagewithprivkey` add a test for it and update the types tables.
Closes #176
=> Change `signmessage` returned signature type

node/CHANGELOG.md, node/README.md, node/src/lib.rs
I noticed with a recent upgrade that the `download` feature flag is no longer auto-enabled with a version selected. I believe that happened here: https://github.com/rust-bitcoin/corepc/pull/45
Just updating the docs here since it took me a second to realize.
=> doc: update docs for now explicit download feature flag

integration_test/README.md
Woops. Include v29 since the PR is in flight.
Fix: #181
=> integtation_test: Fix shell alias in docs

integration_test/tests/network.rs, types/src/model/mod.rs, types/src/model/network.rs, types/src/v18/mod.rs, types/src/v18/network/into.rs, types/src/v18/network/mod.rs, types/src/v19/mod.rs, types/src/v20/mod.rs, types/src/v21/mod.rs, types/src/v22/mod.rs, types/src/v23/mod.rs, types/src/v24/mod.rs, types/src/v25/mod.rs, types/src/v26/mod.rs, types/src/v27/mod.rs, types/src/v28/mod.rs, verify/src/method/v18.rs, verify/src/method/v19.rs, verify/src/method/v20.rs, verify/src/method/v21.rs, verify/src/method/v22.rs, verify/src/method/v23.rs, verify/src/method/v24.rs, verify/src/method/v25.rs, verify/src/method/v26.rs, verify/src/method/v27.rs, verify/src/method/v28.rs
GetNodeAddresses returns an Address.  Create a bitcoin::Address model for it and modify the test to use it.
Implement for v18 to v21. In v22 the return changes, label v22 to v28 as TODO.
=> Add model for getnodeaddresses

Cargo-minimal.lock, Cargo-recent.lock, client/CHANGELOG.md, client/Cargo.toml, integration_test/Cargo.toml, node/CHANGELOG.md, node/Cargo.toml, types/CHANGELOG.md, types/Cargo.toml
In preparation for releasing all three crates bump the version to 0.8.0, add changelog entry, and update the lock files.
=> Release tracking PR: `node`, `client`, and `types` - `v0.8.0`

.github/workflows/pr-labeler.yml
This pull request introduces a GitHub Action workflow that automatically applies labels to pull requests based on the files modified.
**What This Does**
1. Automatically applies labels like **c-node**, **c-client**, **c-integration**, etc.
2. Labeling is based on file path patterns using the labeler GitHub Action
3. Runs on PR events: **opened**, **synchronize**, and **reopened**
i made a PR to test this in my fork: [https://github.com/0xZaddyy/corepc/pulls](url)
=> Add GitHub Action for Automatic Labeling Based on File Changes.

client/src/client_sync/v17/mod.rs, client/src/client_sync/v17/network.rs, client/src/client_sync/v18/mod.rs, client/src/client_sync/v19/mod.rs, client/src/client_sync/v20.rs, client/src/client_sync/v21/mod.rs, client/src/client_sync/v22/mod.rs, client/src/client_sync/v23/mod.rs, client/src/client_sync/v24.rs, client/src/client_sync/v25.rs, client/src/client_sync/v26/mod.rs, client/src/client_sync/v27.rs, client/src/client_sync/v28/mod.rs, client/src/client_sync/v29/mod.rs, integration_test/tests/network.rs
Going by the conversations with tcharding for PR [#116 ](https://github.com/rust-bitcoin/corepc/pull/116) on implementing one method at a time for easier review: This is first method under network section, addnode which is a specific type that returns a (json null). Once this is approved, I’ll proceed with the next one.
=> Implement addnode method and test

.github/workflows/pr-labeler.yml
The workflow file has a lower case `c` at the start of all the labels. Change to uppercase to match the labels in the repo.
=> PR labeler workflow: Change the case of the labels to match the repo

client/src/client_sync/v17/mod.rs, client/src/client_sync/v17/network.rs, client/src/client_sync/v18/mod.rs, client/src/client_sync/v19/mod.rs, client/src/client_sync/v20.rs, client/src/client_sync/v21/mod.rs, client/src/client_sync/v22/mod.rs, client/src/client_sync/v23/mod.rs, client/src/client_sync/v24.rs, client/src/client_sync/v25.rs, client/src/client_sync/v26/mod.rs, client/src/client_sync/v27.rs, client/src/client_sync/v28/mod.rs, client/src/client_sync/v29/mod.rs, integration_test/tests/network.rs
Going by the conversations with tcharding for PR [#116 ](https://github.com/rust-bitcoin/corepc/pull/116) on implementing one method at a time for easier review: This is another method under network section, setban which is a specific type that returns a (json null). Once this is approved, I’ll proceed with the next one.
=> Implement setban method and test

integration_test/tests/wallet.rs, types/src/v17/mod.rs, types/src/v17/wallet/into.rs, types/src/v18/mod.rs, types/src/v18/wallet/into.rs, types/src/v18/wallet/mod.rs, types/src/v19/mod.rs, types/src/v20/mod.rs, types/src/v21/mod.rs, types/src/v22/mod.rs, types/src/v23/mod.rs, types/src/v24/mod.rs, types/src/v25/mod.rs, types/src/v26/mod.rs, types/src/v27/mod.rs, types/src/v28/mod.rs, types/src/v29/mod.rs
While working on [#187](https://github.com/rust-bitcoin/corepc/issues/187), I wrote a test for the listunspent method to better understand the issue. The test timed out in my local environment, so I pushed it here to run in CI and confirm the behavior. I found that although the account field has been deprecated and is no longer included in the response, ListUnspentItem still expects it to be present, which causes a deserialization error.
While writing this test, I also discovered a related issue:
The into_model method is implemented for ListUnspentItem and ListUnspentItemError, but not for the top-level ListUnspent type. This makes it harder to convert the full response into a usable model and limits how we can work with the data.
Closes #187
Closes #189
=> Improve ListUnspent data handling: Fix deserialization & add into_model

client/src/client_sync/v17/mod.rs, client/src/client_sync/v17/network.rs, client/src/client_sync/v18/mod.rs, client/src/client_sync/v19/mod.rs, client/src/client_sync/v20.rs, client/src/client_sync/v21/mod.rs, client/src/client_sync/v22/mod.rs, client/src/client_sync/v23/mod.rs, client/src/client_sync/v24.rs, client/src/client_sync/v25.rs, client/src/client_sync/v26/mod.rs, client/src/client_sync/v27.rs, client/src/client_sync/v28/mod.rs, client/src/client_sync/v29/mod.rs, integration_test/tests/network.rs
Going by the conversations with tcharding for PR [#116 ](https://github.com/rust-bitcoin/corepc/pull/116) on implementing one method at a time for easier review: This is the clearbanned method which is a specific type that returns a (json null). Once this is approved, I’ll proceed with the next one.
=> Implement clearbanned method and test

integration_test/src/lib.rs
We are getting intermittent test failures stating that the node is not available. `node` already includes code that hits the RPC API after the node is up so this is a little surprising. However it doesn't hurt to try waiting a little still.
Just sleep for half a second after each node spins up and see if the intermittent failures go away.
=> integration_test: Pause after node comes up

integration_test/src/lib.rs, node/src/lib.rs
The intermittent integration test failures are caused by race conditions in the creation of the node, wallet or the cookie file. Change `Node::with_conf` to check if there is a problem and retry the section where it occurred, or if that still fails retry the whole process of starting the node.
First patch: 
- Split out some sections into helper functions.
Second patch:
- Remove the loop in `with_conf()` that creates `client`, instead loop over the individual parts.
- Create helper functions for creating the `client`, and creating or loading the client `wallet`, both with their own retry logic.
- Reduce the sleep time between retries to reduce the delay, since it looks like the errors happen over shorter time periods than the existing 1 second wait.
- Add functions to wait until the client …
=> Fix integration test failures by making Node::with_conf more robust

node/src/lib.rs
The feature gates on `Node::create_wallet` and `Node::rpc_url_with_wallet` are not needed.
Remove them.
Closes #214
=> Remove unnecessary feature gate

types/src/v17/mod.rs, types/src/v18/mod.rs, types/src/v19/mod.rs, types/src/v20/mod.rs, types/src/v21/mod.rs, types/src/v22/mod.rs, types/src/v23/mod.rs, types/src/v24/mod.rs, types/src/v25/mod.rs, types/src/v26/mod.rs, types/src/v27/mod.rs, types/src/v28/mod.rs, types/src/v29/mod.rs
This PR updates `returns (std)` to `version` for all methods that have been implemented to return a type which wraps a standard value.
Ref: #116
=> Update 'returns (std)' to 'version' for version methods

client/src/client_sync/v17/mod.rs, client/src/client_sync/v17/network.rs, client/src/client_sync/v18/mod.rs, client/src/client_sync/v19/mod.rs, client/src/client_sync/v20/mod.rs, client/src/client_sync/v21/mod.rs, client/src/client_sync/v22/mod.rs, client/src/client_sync/v23/mod.rs, client/src/client_sync/v24/mod.rs, client/src/client_sync/v25/mod.rs, client/src/client_sync/v26/mod.rs, client/src/client_sync/v27/mod.rs, client/src/client_sync/v28/mod.rs, client/src/client_sync/v29/mod.rs, integration_test/tests/network.rs
The JSON-RPC method `ping` does return null. We want to test this to catch any changes in behavior in future Core versions.
=> Implement ping method and test

types/src/v17/network/mod.rs
This PR fix a typo in the `GetNetTotals` struct field `total_bytes_received`.
=> Correct typo in struct field

client/CHANGELOG.md, contrib/run-bitcoind.sh, fuzz/cycle.sh, integration_test/tests/raw_transactions.rs, node/CHANGELOG.md, node/src/lib.rs, types/CHANGELOG.md, types/src/model/blockchain.rs, types/src/v17/raw_transactions/mod.rs, types/src/v19/blockchain/mod.rs
This PR fixes various typographical errors across the entire codebase. These changes affect code comments, documentation and struct field name where applicable. No functional code has been modified nor affected.
=> Correct typos across the entire codebase

client/src/client_sync/v17/mod.rs, client/src/client_sync/v17/wallet.rs, client/src/client_sync/v18/mod.rs, client/src/client_sync/v19/mod.rs, client/src/client_sync/v20/mod.rs, client/src/client_sync/v21/mod.rs, client/src/client_sync/v22/mod.rs, client/src/client_sync/v23/mod.rs, client/src/client_sync/v24/mod.rs, client/src/client_sync/v25/mod.rs, client/src/client_sync/v26/mod.rs, client/src/client_sync/v27/mod.rs, client/src/client_sync/v28/mod.rs, client/src/client_sync/v29/mod.rs, integration_test/tests/wallet.rs
The JSON-RPC method `abandontransaction` does return null. We want to test this to catch any changes in behavior in future Core versions.
=> Implement abandontransaction and test

client/src/client_sync/v21/wallet.rs, client/src/client_sync/v23/blockchain.rs, client/src/client_sync/v26/blockchain.rs, client/src/client_sync/v26/mining.rs, integration_test/tests/generating.rs, integration_test/tests/mining.rs, integration_test/tests/raw_transactions.rs, types/src/lib.rs, types/src/model/blockchain.rs, types/src/psbt/mod.rs, types/src/v17/blockchain/mod.rs, types/src/v17/mining/mod.rs, types/src/v17/raw_transactions/mod.rs, types/src/v19/blockchain/mod.rs, types/src/v26/blockchain.rs, types/src/v29/mining/mod.rs, verify/src/lib.rs, verify/src/method/v17.rs, verify/src/method/v18.rs, verify/src/method/v19.rs, verify/src/method/v20.rs, verify/src/method/v21.rs
There is a variation in the way the version numbers are written in the docs. Some are preceded by a 0 and some aren't. [Core](https://bitcoin.org/en/version-history) states the versions up to and including 21 with preceding 0, and for 22 and above without.
Change all version numbers in the text to be v0.17 - v0.21, and v22 - v29 to match core.
=> Standardize version number format in docs

client/src/client_sync/v18/mining.rs, client/src/client_sync/v18/mod.rs, client/src/client_sync/v19/mod.rs, client/src/client_sync/v20/mod.rs, client/src/client_sync/v21/mod.rs, client/src/client_sync/v22/mod.rs, client/src/client_sync/v23/mod.rs, client/src/client_sync/v24/mod.rs, client/src/client_sync/v25/mod.rs, client/src/client_sync/v26/mod.rs, client/src/client_sync/v27/mod.rs, client/src/client_sync/v28/mod.rs, client/src/client_sync/v29/mod.rs, integration_test/tests/mining.rs, types/src/v18/mod.rs, types/src/v19/mod.rs, types/src/v20/mod.rs, types/src/v21/mod.rs, types/src/v22/mod.rs, types/src/v23/mod.rs, types/src/v24/mod.rs, types/src/v25/mod.rs, types/src/v26/mod.rs, types/src/v27/mod.rs, types/src/v28/mod.rs, types/src/v29/mod.rs
Add a test and client macro for `submitheader` for v18 and up. There are
no changes up to v29.
Correct the typo that said  `return nothing` to `returns nothing`
=> Implement `submitheader` and test

client/src/client_sync/v17/mod.rs, client/src/client_sync/v17/wallet.rs, client/src/client_sync/v18/mod.rs, client/src/client_sync/v19/mod.rs, client/src/client_sync/v20/mod.rs, client/src/client_sync/v21/mod.rs, client/src/client_sync/v22/mod.rs, client/src/client_sync/v23/mod.rs, client/src/client_sync/v24/mod.rs, client/src/client_sync/v25/mod.rs, client/src/client_sync/v26/mod.rs, client/src/client_sync/v27/mod.rs, client/src/client_sync/v28/mod.rs, client/src/client_sync/v29/mod.rs, integration_test/tests/wallet.rs
The JSON-RPC method `importprivkey` does return null. We want to test this to catch any changes in behavior in future Core versions.
=> Implement importprivkey and test

integration_test/tests/wallet.rs
This PR removes the redundant `if file_path.exists()` check before deleting a temporary file.
As pointed out during review of `backupwallet` integration test [here](https://github.com/rust-bitcoin/corepc/pull/247#discussion_r2148959542), the check is unnecessary.
=> Remove redundant tmp file existence check in wallet integration test

client/src/client_sync/v17/mod.rs, client/src/client_sync/v17/wallet.rs, client/src/client_sync/v18/mod.rs, client/src/client_sync/v19/mod.rs, client/src/client_sync/v20/mod.rs, client/src/client_sync/v21/mod.rs, client/src/client_sync/v22/mod.rs, client/src/client_sync/v23/mod.rs, client/src/client_sync/v24/mod.rs, client/src/client_sync/v25/mod.rs, client/src/client_sync/v26/mod.rs, client/src/client_sync/v27/mod.rs, client/src/client_sync/v28/mod.rs, client/src/client_sync/v29/mod.rs, integration_test/tests/wallet.rs
The JSON-RPC method `importaddress` does return null. We want to test this to catch any changes in behavior in future Core versions.
=> Implement importaddress method and test

types/src/v28/mod.rs, types/src/v29/mod.rs
The module files were all there but the module was undeclared and unused, v26 was still being reexported in v28 and v29.
Declare the module and update the reexports.
=> Enable the v28 `raw_transaction` module

integration_test/README.md
And I always forget that the integration test crate cannot be built with all features enabled.
Add a section to the README in an attempt to save poor future Tobin the time to work this out again.
=> integration test: Document incompatibility of `--all-features`

contrib/lint-integtation-tests.sh
The integration test crate is not part of the workspace and also cannot be built wit all features so linting it must be done for each feature.
Add a script that runs the linter.
=> Add script to lint integration test

integration_test/tests/blockchain.rs, integration_test/tests/network.rs, integration_test/tests/wallet.rs
Adds `let _: () = ...` to all integration test cases where client functions return `()`, making it obvious that these functions return no value.
Closes #256.
=> Annotate null-returning integration test functions with ()

integration_test/tests/mining.rs, integration_test/tests/network.rs, integration_test/tests/raw_transactions.rs, integration_test/tests/util.rs, integration_test/tests/wallet.rs
A new script to lint the integration tests is being added in #258.
Run the script and fix all the lint errors.
=> Fix clippy lints in `integration_test`

client/src/client_sync/v17/mod.rs, client/src/client_sync/v17/wallet.rs, client/src/client_sync/v18/mod.rs, client/src/client_sync/v19/mod.rs, client/src/client_sync/v20/mod.rs, client/src/client_sync/v21/mod.rs, client/src/client_sync/v22/mod.rs, client/src/client_sync/v23/mod.rs, client/src/client_sync/v24/mod.rs, client/src/client_sync/v25/mod.rs, client/src/client_sync/v26/mod.rs, client/src/client_sync/v27/mod.rs, client/src/client_sync/v28/mod.rs, client/src/client_sync/v29/mod.rs, integration_test/tests/wallet.rs
The JSON-RPC method `importpubkey` does not return anything. We want to test this to catch any changes in behavior in future Core versions.
=> Implement importpubkey method and test

.github/workflows/README.md, .github/workflows/rust.yaml, contrib/lint-verify.sh, justfile, verify/src/main.rs, verify/src/versioned.rs
Do a bunch of preparation and then add commands to the already present lint job in CI to lint `verify` and `integration_tests`.
Close: #236
=> Lint non-workspace crates in CI

client/src/client_sync/v17/mod.rs, client/src/client_sync/v17/wallet.rs, client/src/client_sync/v18/mod.rs, client/src/client_sync/v19/mod.rs, client/src/client_sync/v20/mod.rs, client/src/client_sync/v21/mod.rs, client/src/client_sync/v22/mod.rs, client/src/client_sync/v23/mod.rs, client/src/client_sync/v24/mod.rs, client/src/client_sync/v25/mod.rs, client/src/client_sync/v26/mod.rs, client/src/client_sync/v27/mod.rs, client/src/client_sync/v28/mod.rs, client/src/client_sync/v29/mod.rs, integration_test/tests/wallet.rs
The JSON-RPC method `importwallet` does not return anything. We want to test this to catch any changes in behavior in future Core versions.
=> Implement importwallet method and test

client/src/client_sync/v17/mod.rs, client/src/client_sync/v17/wallet.rs, client/src/client_sync/v18/mod.rs, client/src/client_sync/v19/mod.rs, client/src/client_sync/v20/mod.rs, client/src/client_sync/v21/mod.rs, client/src/client_sync/v22/mod.rs, client/src/client_sync/v23/mod.rs, client/src/client_sync/v24/mod.rs, client/src/client_sync/v25/mod.rs, client/src/client_sync/v26/mod.rs, client/src/client_sync/v27/mod.rs, client/src/client_sync/v28/mod.rs, client/src/client_sync/v29/mod.rs, integration_test/tests/wallet.rs
The JSON-RPC method `removeprunedfunds` does not return anything. We want to test this to catch any changes in behavior in future Core versions.
=> Implement removeprunedfunds method and test

client/src/client_sync/v17/wallet.rs
Correct name of method in documentation for `lockunspent` client function.
=> Correct method name for lockunspent client doc

client/src/client_sync/v17/mod.rs, client/src/client_sync/v17/wallet.rs, client/src/client_sync/v18/mod.rs, client/src/client_sync/v19/mod.rs, client/src/client_sync/v20/mod.rs, client/src/client_sync/v21/mod.rs, client/src/client_sync/v22/mod.rs, client/src/client_sync/v23/mod.rs, client/src/client_sync/v24/mod.rs, client/src/client_sync/v25/mod.rs, client/src/client_sync/v26/mod.rs, client/src/client_sync/v27/mod.rs, client/src/client_sync/v28/mod.rs, client/src/client_sync/v29/mod.rs, integration_test/tests/wallet.rs
The JSON-RPC method `walletpassphrase` does not return anything. We want to test this to catch any changes in behavior in future Core versions.
=> Implement walletpassphrase method and test

client/src/client_sync/v17/mod.rs, client/src/client_sync/v17/wallet.rs, client/src/client_sync/v18/mod.rs, client/src/client_sync/v19/mod.rs, client/src/client_sync/v20/mod.rs, client/src/client_sync/v21/mod.rs, client/src/client_sync/v22/mod.rs, client/src/client_sync/v23/mod.rs, client/src/client_sync/v24/mod.rs, client/src/client_sync/v25/mod.rs, client/src/client_sync/v26/mod.rs, client/src/client_sync/v27/mod.rs, client/src/client_sync/v28/mod.rs, client/src/client_sync/v29/mod.rs, integration_test/tests/wallet.rs
The JSON-RPC method `walletpassphrasechange` does not return anything. We want to test this to catch any changes in behavior in future Core versions.
=> Implement walletpassphrasechange method and test

jsonrpc/src/client.rs, jsonrpc/src/error.rs, jsonrpc/src/http/minreq_http.rs, jsonrpc/src/http/simple_http.rs
Use AI to go through every file in jsonrpc and add missing full stops to the rust docs.
Part of the fix for issue #296
=> Add full stops to rustdocs in jsonrpc

node/src/lib.rs
Use AI to go through every file in node and add missing full stops to the rust docs.
Together with #302, #303 and #304 Closes #296
=> Add full stops to rustdocs in node

types/src/v17/network/mod.rs, types/src/v17/wallet/mod.rs, types/src/v20/network.rs, types/src/v22/network.rs, types/src/v28/raw_transactions/mod.rs, types/src/v28/wallet/mod.rs, types/src/v29/blockchain/mod.rs
Use AI to go through every file in types and add missing full stops to the rust docs.
Only change this crates rustdocs, not anything preceded with `/// >` that comes from core help for the RPCs.
Part of the fix for issue #296
=> Add full stops to rustdocs in types

client/src/client_sync/v17/mod.rs, client/src/client_sync/v21/mod.rs, integration_test/tests/wallet.rs, types/src/lib.rs, types/src/model/wallet.rs, types/src/psbt/mod.rs, types/src/v17/raw_transactions/mod.rs, types/src/v17/wallet/into.rs, types/src/v17/wallet/mod.rs, types/src/v20/wallet/into.rs, types/src/v20/wallet/mod.rs, types/src/v21/network/mod.rs, types/src/v22/network.rs, types/src/v22/raw_transactions/mod.rs, types/src/v23/network.rs, types/src/v23/raw_transactions/mod.rs, types/src/v24/network.rs, types/src/v24/raw_transactions/into.rs, types/src/v24/raw_transactions/mod.rs, types/src/v24/wallet/into.rs, types/src/v24/wallet/mod.rs, types/src/v26/network.rs
Some of the renaming of the rpc returned fields was inconsistent.
Go through them all and make them them consistent.
Fixes the issue #298, but not closing it with this PR since there is an open PR that is also affected.
=> Make serde renames consistent

types/src/model/blockchain.rs
There are unnecessary comments in the struct definition saying parsed or converted into.
Remove them.
Closes #299
=> Remove unnecessary "parsed into" in rustdocs

client/src/client_sync/v23/blockchain.rs, client/src/client_sync/v23/mod.rs, client/src/client_sync/v23/wallet.rs, client/src/client_sync/v24/mod.rs, client/src/client_sync/v25/mod.rs, client/src/client_sync/v26/mod.rs, client/src/client_sync/v27/mod.rs, client/src/client_sync/v28/mod.rs, client/src/client_sync/v29/mod.rs, integration_test/tests/blockchain.rs, integration_test/tests/wallet.rs, types/src/model/blockchain.rs, types/src/model/mod.rs, types/src/v23/blockchain/error.rs, types/src/v23/blockchain/into.rs, types/src/v23/blockchain/mod.rs, types/src/v23/mod.rs, types/src/v23/wallet/mod.rs, types/src/v24/mod.rs, types/src/v25/mod.rs, types/src/v26/mod.rs, types/src/v27/mod.rs, types/src/v28/mod.rs, types/src/v29/mod.rs
Go through all the TODO in the v23 types table. Add all the missing RPCs.
- Add getblockfrompeer macro and test
- Add restorewallet struct, macro and test
- Add newkeypool macro and test
- Add getdeploymentinfo struct, model and test
- Run the formatter
=> Address all TODO in v23

client/src/client_sync/error.rs, client/src/client_sync/v17/blockchain.rs, client/src/client_sync/v17/generating.rs, client/src/client_sync/v17/mining.rs, client/src/client_sync/v17/mod.rs, client/src/client_sync/v17/network.rs, client/src/client_sync/v17/raw_transactions.rs, client/src/client_sync/v17/util.rs, client/src/client_sync/v17/wallet.rs, client/src/client_sync/v18/network.rs, client/src/client_sync/v18/raw_transactions.rs, client/src/client_sync/v18/util.rs, client/src/client_sync/v19/blockchain.rs, client/src/client_sync/v19/wallet.rs, client/src/client_sync/v20/generating.rs, client/src/client_sync/v21/generating.rs, client/src/client_sync/v21/wallet.rs, client/src/client_sync/v22/wallet.rs, client/src/client_sync/v23/blockchain.rs, client/src/client_sync/v25/generating.rs, client/src/client_sync/v26/blockchain.rs, client/src/client_sync/v26/mining.rs, client/src/client_sync/v26/raw_transactions.rs, client/src/client_sync/v28/raw_transactions.rs, client/src/client_sync/v29/blockchain.rs
Use AI to go through every file in client and add missing full stops to the rust docs.
There is one typo it also fixed without asking that I noticed.
Part of the fix for issue #296
=> Add full stops to rustdocs in client

node/build.rs
Extension of [PR #71](https://github.com/rust-bitcoin/corepc/pull/71), which introduced initial support for codesigning in the `node` crate. As of version 29, Bitcoin Core has [begun codesigning](https://github.com/bitcoin/bitcoin/pull/31407) the `bitcoind` binary for macOS users. This broke the current logic of the node crate here because we're currently signing every time. This results in the build step of this crate panicking with:
```
--- stderr
..../target/debug/build/corepc-node-ab8800f75cc98512/out/bitcoin/bitcoin-29.0/bin/bitcoind: is already signed
```
To fix this, I've added some simple validation code that checks if the binary is already signed and subsequently skips the codesign step.
Verified on macOS Sequoia 15.5 (24F74) with M3 silicon using:
```
cargo test --features …
```
=> Only codesign bitcoind if necessary

client/src/client_sync/v25/blockchain.rs, client/src/client_sync/v25/mod.rs, client/src/client_sync/v26/mod.rs, client/src/client_sync/v27/mod.rs, client/src/client_sync/v28/mod.rs, client/src/client_sync/v29/mod.rs, integration_test/tests/blockchain.rs, types/src/model/blockchain.rs, types/src/model/mod.rs, types/src/v25/blockchain/error.rs, types/src/v25/blockchain/into.rs, types/src/v25/blockchain/mod.rs, types/src/v25/mod.rs, types/src/v26/mod.rs, types/src/v27/mod.rs, types/src/v28/mod.rs, types/src/v29/mod.rs
Go through all the TODO in the v25 types table. Add all the missing RPCs.
One missing RPC in v25, `scanblocks` which has 3 different return shapes, one each  for `abort`, `start` and `status`. Create a struct for each one.
`status` returns null if there is no ongoing scan, use an Option in the client macro to deal with this.
=> Address all TODO in v25

contrib/run-bitcoind.sh
On more than one occasion I have tried to start all nodes by passing `run all` or `start all` instead of just `all`.
Handle this the same as passing `all` as the argument to the script.
=> Add support for run-bitcoind.sh start all

integration_test/tests/network.rs, node/src/lib.rs, types/src/v17/network/mod.rs, types/src/v18/network/mod.rs, types/src/v19/network/mod.rs, types/src/v21/mod.rs, types/src/v21/network/mod.rs, types/src/v22/mod.rs, types/src/v22/network.rs, types/src/v23/mod.rs, types/src/v23/network.rs, types/src/v24/mod.rs, types/src/v24/network.rs, types/src/v25/mod.rs, types/src/v26/network.rs
In #310 I got mixed up and added fields to the v17 types `GetPeerInfo` struct that do not appear in the docs.
This was masked by using `Option`. And not helped by the fact that a bunch of other `Option`s are used because the docs do not match what Core returns.
These bugs propagated up through the version numbers. Go over them all and sort it out.
Note also that we were incorrectly re-exporting `PeerInfo` from v19 even though the `PeerInfo` struct that was actually being used is found in the version specific file along with `GetPeerInfo` - face palm.
And finally, remove all the 'vXY and later' docs, this is implied by the module. These sorts of comments should only be found in `model`.
=> Improve `GetPeerInfo`

types/src/v27/mod.rs, types/src/v27/network/mod.rs, types/src/v28/mod.rs, types/src/v29/mod.rs
Go through all the TODO in the v26 types table.
- Redefine `getnodeaddresses`: There were return field changes in v27. Redefine the struct and update the reexports. Update the types tables.
- Run the formatter: Done separately to make it easier to see the changes in patch 1.
DRAFT because on top of #321. This PR is the last 2 patches.
=> Address all TODO in v27

client/src/client_sync/v29/mod.rs, client/src/client_sync/v29/util.rs, integration_test/tests/util.rs, types/src/model/mod.rs, types/src/model/util.rs, types/src/v29/mod.rs, types/src/v29/util.rs
One TODO in v29 for `deriveaddresses`
The change is that it now supports multipath descriptors when calling `deriveaddresses`.
Add a new struct, model and client function for DeriveAddressesMultipath.
Update the test for v29 to check a multipath descriptor.
=> Address all TODO in v29

client/src/client_sync/v17/raw_transactions.rs, integration_test/tests/raw_transactions.rs, types/src/model/raw_transactions.rs, types/src/v17/mod.rs, types/src/v17/raw_transactions/into.rs, types/src/v17/raw_transactions/mod.rs, types/src/v18/mod.rs, types/src/v19/mod.rs, types/src/v20/mod.rs, types/src/v21/mod.rs, types/src/v22/mod.rs, types/src/v23/mod.rs, types/src/v24/mod.rs, types/src/v25/mod.rs, types/src/v26/mod.rs, types/src/v27/mod.rs, types/src/v28/mod.rs, types/src/v29/mod.rs
Fix the test for `finalizepsbt`.
The field `psbt` is optional for all versions, the help does not specifically say `optional` until v23, before that it says `if not extracted`.
Make `psbt` an `Option`.
=> Test finalizepsbt

integration_test/tests/wallet.rs, types/src/v17/wallet/into.rs, types/src/v17/wallet/mod.rs
`listaddressgroupings` was untested.
- Add a test for it that returns a non empty list. But now with this test there is an error because "when Serde deserializes from a JSON array (a sequence), it uses positional fields and requires the sequence length to match the number of struct fields exactly" (AI quote). Which causes an error when the optional field `label` is not returned.
- Change the struct to an enum with 2 fields, one for 2 returned items and one for 3.
No changes to the RPC return fields up to v29.
=> Test `listaddressgroupings`

client/src/client_sync/v21/hidden.rs, client/src/client_sync/v21/mod.rs, client/src/client_sync/v22/mod.rs, client/src/client_sync/v23/mod.rs, client/src/client_sync/v24/mod.rs, client/src/client_sync/v25/mod.rs, client/src/client_sync/v26/mod.rs, client/src/client_sync/v27/mod.rs, client/src/client_sync/v28/mod.rs, client/src/client_sync/v29/mod.rs
The macro name had a single underscore where it requried two.
Fix the name.
=> Fix `addpeeraddress` client macro name

integration_test/tests/wallet.rs, types/src/v17/mod.rs, types/src/v18/mod.rs, types/src/v19/mod.rs, types/src/v20/mod.rs, types/src/v21/mod.rs, types/src/v22/mod.rs, types/src/v23/mod.rs, types/src/v24/mod.rs, types/src/v25/mod.rs, types/src/v26/mod.rs, types/src/v27/mod.rs, types/src/v28/mod.rs, types/src/v29/mod.rs
`listwallets` is implemented but untested. Also the `getunconfirmedbalance` test was added in a previous PR but the types table was not updated.
- Remove `getunconfirmedbalance` `UNTESTED` from the types table.
- Add a test for `listwallet` and update the types table.
=> Test `listwallets`

client/src/client_sync/v18/raw_transactions.rs, integration_test/tests/raw_transactions.rs, types/src/v18/mod.rs, types/src/v19/mod.rs, types/src/v20/mod.rs, types/src/v21/mod.rs, types/src/v22/mod.rs, types/src/v23/mod.rs, types/src/v24/mod.rs, types/src/v25/mod.rs, types/src/v26/mod.rs, types/src/v27/mod.rs, types/src/v28/mod.rs, types/src/v29/mod.rs
`utxoupdatepsbt` and `joinpsbts` are implemented but untested. The client macro for `utxoupdatepsbt` had a typo and the incorrect return type. Neither RPC has any return changes up to v29.
- Fix the typo and return type in `utxoupdatepsbt` client macro.
- Test `utxoupdatepsbt` and update the types table.
- Test `joinpsbts` and update the types table.
=> Test `utxoupdatepsbt` and `joinpsbts`

integration_test/tests/signer.rs, types/src/v22/mod.rs, types/src/v22/signer.rs, types/src/v23/mod.rs, types/src/v24/mod.rs, types/src/v25/mod.rs, types/src/v26/mod.rs, types/src/v27/mod.rs, types/src/v28/mod.rs, types/src/v29/mod.rs
`enumeratesigners` is implemented but not tested. Also the v22 help is not correct, it gives incorrect field names which were implemented in the struct. They are correct in v23 and onwards help.
- Fix the v22 struct names.
- Add a test and update the types table.
=> Test `enumeratesigners`

client/src/client_sync/v17/wallet.rs, client/src/client_sync/v21/mod.rs, client/src/client_sync/v21/wallet.rs, client/src/client_sync/v22/mod.rs, client/src/client_sync/v23/mod.rs, client/src/client_sync/v24/mod.rs, client/src/client_sync/v25/mod.rs, client/src/client_sync/v26/mod.rs, client/src/client_sync/v27/mod.rs, client/src/client_sync/v28/mod.rs, client/src/client_sync/v29/mod.rs, integration_test/tests/wallet.rs, types/src/model/mod.rs, types/src/model/wallet.rs, types/src/v17/mod.rs, types/src/v18/mod.rs, types/src/v19/mod.rs, types/src/v20/mod.rs, types/src/v21/mod.rs, types/src/v21/wallet/into.rs, types/src/v21/wallet/mod.rs, types/src/v22/mod.rs, types/src/v23/mod.rs, types/src/v24/mod.rs, types/src/v25/mod.rs, types/src/v26/mod.rs, types/src/v27/mod.rs, types/src/v28/mod.rs, types/src/v29/mod.rs
`sendmany` is implemented for v17 but untested and it has a new verbose return type in v18.
The client macro sends the amount in sats but the RPC takes BTC.
- Add the verbose struct to v18 and model.
- Update the client macro.
- Add a verbose client macro, test and update the types table.
=> Test `sendmany`

types/src/model/blockchain.rs, types/src/model/util.rs, types/src/model/wallet.rs, types/src/v17/blockchain/mod.rs, types/src/v17/wallet/mod.rs, types/src/v21/wallet/mod.rs, types/src/v22/network.rs, types/src/v23/wallet/mod.rs, types/src/v28/wallet/mod.rs
Some of the structs and enums are not in alphabetical order.
- Order them all by the RPC name, with sub structs directly below. Code moves only, no content changes.
Two structs had incorrect RPC names in their rustdocs.
- Correct the rustdocs.
=> Reorder types structs in alphabetical order

types/src/lib.rs, types/src/model/blockchain.rs, types/src/model/mod.rs, types/src/v29/blockchain/error.rs, types/src/v29/blockchain/into.rs
`ScriptPubKey` has fields that can be modelled with rust-bitcoin types. And says in it's own rustdoc ```The `mtype::ScriptPubkey` mirrors this design```, but there is none. 
Two RPCs use this type, `getdescriptoractivity` and `gettxout`. The `GetTxOut` model extracts individual fields from the `ScriptPubKey` to create a `TxOut` and `Address`, and does not model a `ScriptPubKey` type.
- Add the `ScriptPubKey` model, error and into function.
- Use the model in `GetDescriptorActivity`.
=> Add ScriptPubKey model

types/src/model/blockchain.rs, types/src/model/generating.rs, types/src/model/mining.rs, types/src/model/network.rs, types/src/model/raw_transactions.rs, types/src/model/util.rs, types/src/model/wallet.rs
The attribute was added to catch mistakes in what core returns compared to what is in the structs. This has no meaning in `model` since they are internal conversions of the version specific types.
Remove the attribute from all `model` types.
Closes #373
=> Remove `serde-deny-unknown-fields` from `model` types

Cargo-minimal.lock, Cargo-recent.lock, client/CHANGELOG.md, client/Cargo.toml, node/CHANGELOG.md, node/Cargo.toml, types/CHANGELOG.md, types/Cargo.toml
In preparation for release add a changelog entry, bump the version, and update the lockfiles.
This is for all three released crates. FTR because they depend on each other release of `types` triggers release of the others too (if I'm not mistaken).
=> Bump versions to 0.10.0

client/Cargo.toml, node/Cargo.toml
I just tried to publish `corepc-client 0.10.0` and got an error from `cargo`.
error: all dependencies must have a version specified when publishing.
We recently switched to using `path` instead of versions, seems like this was wrong.
=> Specify version of dependencies instead of path
